- hosts: "{{ v_host | default('ocp-svc') }}"
  user: ocp
  become: yes
  vars:
    hostmachine: "{{ v_host | default('ocp-svc') }}"
    registry_user: "admin"
    registry_pass: "RandomKey135" # not all passowrd combinations works
    OCP_RELEASE: 4.19.4 # $(oc version | grep "4.19" | awk '{print $3}')
    LOCAL_REGISTRY: "registry.ocp.local:7443"
    LOCAL_REPOSITORY: "ocp4"
    PRODUCT_REPO: "openshift-release-dev"
    LOCAL_SECRET_JSON: "/ocp/pull-secret.json"
    RELEASE_NAME: "ocp-release"
    ARCHITECTURE: "x86_64" #x86_64 or aarch64
    XDG_RUNTIME_DIR: "/ocp/data/mirror"
    bin_path: "/ocp/installer"
    script_dir: /ocp/installer/python-scripts
  roles:
    - role: ocp-configure-clone-quay

# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory/hosts -e "v_host=ocp-svc" clone-quay-registry.yaml -kK -vv
