- name: Installing packages
  include_tasks: reusable/ubuntu/install.yaml
  vars:
    packages:
      - bind9
      - bind9utils
      - bind9-utils
      - bind9-doc
      - dnsutils

- name: "Copying {{ item.src }}"
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    directory_mode: "{{ item.directory_mode }}"
  loop:
    - src: "../files/named.conf"
      dest: "/etc/bind/"
      mode: "0644"
      directory_mode: no
    - src: "../files/named.conf.options"
      dest: "/etc/bind/"
      mode: "0644"
      directory_mode: no
    - src: "../files/named.conf.local"
      dest: "/etc/bind/"
      mode: "0644"
      directory_mode: no
    - src: "../files/zones/"
      dest: "/etc/bind/zones/"
      mode: "0644"
      directory_mode: yes

- name: "Applying changes and starting DNS server"
  become: yes
  shell: |
    chmod 755 /etc/bind/zones
    # We will allow 53 (DNS port) for internal and external firewall
    # for OCP 4.9 and later 53/tcp is required
    firewall-cmd --add-port=53/udp --zone=internal --permanent
    firewall-cmd --add-port=53/tcp --zone=external --permanent
    firewall-cmd --reload

    systemctl enable named
    systemctl start named
    systemctl status named

- name: "Verifying DNS"
  become: yes
  shell: |
    systemctl restart named

    # Confirm dig now sees the correct DNS results by using the DNS Server running locally
    dig ocp.local
    # The following should return the answer bootstrap.cluster.ocp.local from the local server
    dig -x 192.168.56.100

- name: Purge bind
  become: yes
  shell: |
    apt-get remove --purge bind* -y
    rm -rf /var/cache/bind
    rm -rf /etc/bind
  when: purge_dns is defined
  tags:
    - purge_dns  

